### ISSUE TITLE
Getting error accessing the side panel in admin area

### ISSUE THREAD

**Issue by cnneinn** [tauseedzaman/hospitalMS#10]
> Call to undefined function _() (View: C:\laragon\www\hms\resources\views\livewire\admins\rooms.blade.php)

**Comment by ahmedhassan399** [comment]
The dashboard is not working and returns to the home page again

**Comment by Nihirz** [comment]
You can change it in your project Find the  **home** in  **RouteServiceProvider** then add your URL. Here I share the example bellow 

**public const HOME = '/admin/settings';**

**Comment by Nihirz** [comment]
I updated the code, when the admin merges you can access it !!!
