### ISSUE TITLE
Undefined array key "id" after a fresh install

### ISSUE THREAD

**Issue by 2dotsdev** [tauseedzaman/hospitalMS#17]
<img width="1921" alt="image" src="https://github.com/tauseedzaman/hospitalMS/assets/155329274/af226ed9-d311-413c-ba2c-bf8620962506">

Not sure why. pop right after login

**Comment by tauseedzaman** [comment]
HI, buddy just reinstalled this project on my machine.. maybe there where some bugs back then .. as I am making updates each week.. so when you log in you should get redirected to this page..
![image](https://github.com/tauseedzaman/hospitalMS/assets/64689921/ad05d62b-f3ee-4e37-b5d5-2da66f005fad)
