### ISSUE TITLE
Password field added in "Add doctor" form its for?

### ISSUE THREAD

**Issue by meghakundu** [tauseedzaman/hospitalMS#20]
This is admin side role part of the project, right! So or even-though there needs to be link between employees and users table, remove common fields from employees and users table. If its right kindly reply.
There were other issues in pages like register form,departments,hods, which i have fixed already. If its required, kindly let know as a contributor to this. I will be glad enough.

**Comment by tauseedzaman** [comment]
sorry.. for a bit late reply.. but yeah feel free to open a full request to this repo.. I am working on this for a youtube playlist.. so its taking longer for your contribution is appriacted ;)

**Comment by meghakundu** [comment]
> sorry.. for a bit late reply.. but yeah feel free to open a full request to this repo.. I am working on this for a youtube playlist.. so its taking longer for your contribution is appriacted ;)

But you need to send invite for same, if you wish me to help with you in this! @tauseedzaman

**Comment by tauseedzaman** [comment]
what are you talking about ? just clone the repo. create a new branch make the changes you want, push to github . then from your github repo open full request to this main repo.. and thats set..
here is a video that might help you understand .. 
[https://www.youtube.com/watch?v=vEcT6JIFji0](https://www.youtube.com/watch?v=vEcT6JIFji0)

**Comment by meghakundu** [comment]
> what are you talking about ? just clone the repo. create a new branch make the changes you want, push to github . then from your github repo open full request to this main repo.. and thats set.. here is a video that might help you understand .. https://www.youtube.com/watch?v=vEcT6JIFji0

ok thanks

**Comment by meghakundu** [comment]
*This is the thing i wish to mention. Can please guide*
$ git push --set-upstream origin dev
remote: Permission to tauseedzaman/hospitalMS.git denied to meghakundu.
fatal: unable to access 'https://github.com/tauseedzaman/hospitalMS.git/':
The requested URL returned error: 403

**Comment by tauseedzaman** [comment]
you are pushing directly to the main repo.. man.. follow the steps mentioned in Laravel daily video to contribute to any open-source project, ;)

**Comment by meghakundu** [comment]
Thanks for the tip!
