### ISSUE TITLE
doesn't run

### ISSUE THREAD

**Issue by PicsooEU** [tauseedzaman/hospitalMS#23]
Hi, doesn't run, here is the error :

ErrorException
Undefined array key "icon" (View: D:\xampp\htdocs\laravel\hospitalMS\project\resources\views\layouts\app.blade.php)

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
D:\xampp\htdocs\laravel\hospitalMS\project\resources\views/layouts/app.blade.php:23

table 'settings' is empty; can you provide a database with minimum values ?

thanks,
Domi.

**Comment by tauseedzaman** [comment]
Follow the installation instructions given in `readme.md` file.. seems like you have not seeded the data

**Comment by PicsooEU** [comment]
yes but there is no data to put in the database; better way to provide them too ... but meanwhile, I have created a database with some data and it works - so thanks for sharing your project, very nice.
have a nice ay,
Domi.
