### ISSUE TITLE
Login Credentials

### ISSUE THREAD

**Issue by joegeoffrey** [tauseedzaman/hospitalMS#9]
Hello there, thank you for the work on this development. Do you mind sharing the default logins to the super admin? Thank you

**Comment by tlshifat** [comment]
@joege

> Hello there, thank you for the work on this development. Do you mind sharing the default logins to the super admin? Thank you
```

  'email' =>'tauseed@test.com'
  'password' =>'tauseed'
```

**Comment by DineshGuptaa** [comment]
Pp

> @JoeGe
> 
> > Hello there, thank you for the work on this development. Do you mind sharing the default logins to the super admin? Thank you
> 
> ```
> 
>   'email' =>'tauseed@test.com'
>   'password' =>'tauseed'
> ```
I have deployed code on my local environment. I am learning Laravel.
Please share admin access URL

Thanks

**Comment by joegeoffrey** [comment]
Slash the URL of the local setup with login.
E.g. localhost/hospitalms/login

**Comment by DineshGuptaa** [comment]
> Slash the URL of the local setup with login. E.g. localhost/hospitalms/login
For its
Http://127.0.0.1:8000/login
After that I can see **admin area** on the top menu items
Thanks a lot 👍

**Comment by TahmedurRahman-bro** [comment]
how to login to admin panel?
it's not working

**Comment by Mr-Shivam-Gupta** [comment]
firstly use you have to use  this command  " php artisan db:seed "
then  goto to your database  and change the role to admin

**Comment by tauseedzaman** [comment]
for retesting just re-installed the app guys.. and works fine.. follow the installation instructions provided in readme.md
